"""Pre/post matching balance tables for PSM A and B (grouped, decorated LaTeX)."""
import pandas as pd, numpy as np
from pathlib import Path
ANA = Path("/Volumes/Niels 2/MIMIC/physionet.org/files/mimiciv/3.1/analysis/epilepsy_psych")
OUT = ANA / "psm_results"

df = pd.read_csv(ANA / "epilepsy_patient_cohort_psm.csv")

GROUPS = [
    ("Demographics", [
        ("anchor_age", "Age, mean (years)", False),
        ("female",     "Female",            True),
    ]),
    ("Insurance", [
        ("ins_Medicare", "Medicare", True),
        ("ins_Medicaid", "Medicaid", True),
        ("ins_Private",  "Private",  True),
        ("ins_Other",    "Other",    True),
    ]),
    ("Epilepsy severity / refractoriness", [
        ("n_asms",      "Unique ASMs, mean (count)", False),
        ("intractable", "Drug-resistant code (G40.x1)", True),
        ("focal",       "Focal epilepsy", True),
        ("se",          "Status epilepticus history", True),
        ("n_epi_hadm",  "Epilepsy admissions, mean (count)", False),
    ]),
]

def fmt(v, is_pct):
    return f"{v*100:.1f}" if is_pct else f"{v:.2f}"

def smd(a, b):
    a = np.asarray(a, float); b = np.asarray(b, float)
    s = np.sqrt((a.var() + b.var())/2)
    return (a.mean() - b.mean())/s if s > 0 else 0.0

def hi(s, cond):
    return r"\textbf{" + s + r"}" if cond else s

def build_csv(label, base, exclude=()):
    pairs = pd.read_csv(OUT / f"matched_pairs_{label}.csv")
    matched_t = base.set_index("subject_id").loc[pairs["surg_subject"]]
    matched_c = base.set_index("subject_id").loc[pairs["ctrl_subject"]]
    pre_t = base[base["surgical"] == 1]
    pre_c = base[base["surgical"] == 0]
    rows = []
    for grp, items in GROUPS:
        for var, lab, is_pct in items:
            if var in exclude or var not in base.columns: continue
            rows.append({
                "Group": grp, "Variable": lab, "is_pct": is_pct,
                "Surg_pre": pre_t[var].mean(), "Nonsurg_pre": pre_c[var].mean(),
                "SMD_pre":  smd(pre_t[var], pre_c[var]),
                "Surg_post": matched_t[var].mean(), "Nonsurg_post": matched_c[var].mean(),
                "SMD_post":  smd(matched_t[var], matched_c[var]),
            })
    out = pd.DataFrame(rows)
    out.to_csv(OUT / f"balance_prepost_{label}.csv", index=False)
    return out, len(pre_t), len(pre_c), len(pairs)

def latex(out, label, n_t, n_c, n_pairs, caption):
    lines = [
        r"\begin{table}[H]\centering",
        rf"\caption{{{caption}}}",
        rf"\label{{tab:balance_prepost_{label}}}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        rf" & \multicolumn{{3}}{{c}}{{\textbf{{Before matching}} ({n_t} surg \textbar{{}} {n_c} non-surg)}} & \multicolumn{{3}}{{c}}{{\textbf{{After matching}} ({n_pairs} pairs)}} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"\textbf{Variable} & Surg & Non-surg & $|$SMD$|$ & Surg & Non-surg & $|$SMD$|$ \\",
        r"\midrule",
    ]
    last_grp = None
    for _, r in out.iterrows():
        if r["Group"] != last_grp:
            lines.append(rf"\addlinespace[2pt]\multicolumn{{7}}{{l}}{{\textit{{{r['Group']}}}}}\\")
            last_grp = r["Group"]
        is_pct = bool(r["is_pct"])
        sp = abs(r["SMD_pre"]); spo = abs(r["SMD_post"])
        lines.append(
            f"\\quad {r['Variable']} & "
            f"{fmt(r['Surg_pre'], is_pct)} & {fmt(r['Nonsurg_pre'], is_pct)} & "
            f"{hi(f'{sp:.3f}', sp >= 0.10)} & "
            f"{fmt(r['Surg_post'], is_pct)} & {fmt(r['Nonsurg_post'], is_pct)} & "
            f"{hi(f'{spo:.3f}', spo >= 0.10)} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\vspace{2pt}\par\footnotesize\textit{Note}: Continuous variables shown as means; categorical as percentages. Bold $|$SMD$|$ values exceed the 0.10 imbalance threshold.",
        r"\end{table}",
    ]
    return "\n".join(lines)

A, na_t, na_c, na_p = build_csv("A_full", df)
B, nb_t, nb_c, nb_p = build_csv("B_intractable", df[df["intractable"]==1], exclude=("intractable",))

tex = "% Auto-generated by 06_balance_prepost.py\n" + \
    latex(A, "A_full", na_t, na_c, na_p,
          "Covariate balance before and after 1:1 propensity-score matching --- Analysis A (full cohort).") + \
    "\n\n" + \
    latex(B, "B_intractable", nb_t, nb_c, nb_p,
          "Covariate balance before and after 1:1 propensity-score matching --- Analysis B (intractable-only sensitivity).")

(ANA/"overleaf"/"sections_psm"/"balance_prepost.tex").write_text(tex)
print("wrote balance_prepost.tex")

# ---------- Logistic regression table ----------
lr_full = pd.read_csv(OUT / "logreg_full.csv")
lr_match = pd.read_csv(OUT / "logreg_matched_A.csv")
def lr_block(df_):
    rows = []
    for _, r in df_.iterrows():
        if r["term"] == "(Intercept)": continue
        ci = f"({r['OR_lo']:.2f}--{r['OR_hi']:.2f})"
        p  = "$<$0.001" if r["p"] < .001 else f"{r['p']:.3f}"
        rows.append(f"\\quad {r['term']} & {r['OR']:.2f} & {ci} & {p} \\\\")
    return rows

lines = [
    r"\begin{table}[H]\centering",
    r"\caption{Logistic regression for any psychiatric comorbidity. Predictors: surgical status, age, sex.}",
    r"\label{tab:logreg}",
    r"\small",
    r"\begin{tabular}{lccc}",
    r"\toprule",
    r"\textbf{Predictor} & \textbf{OR} & \textbf{95\% CI} & \textbf{$p$} \\",
    r"\midrule",
    rf"\multicolumn{{4}}{{l}}{{\textit{{Full cohort (n={int(df.shape[0])})}}}}\\",
] + lr_block(lr_full) + [
    r"\addlinespace",
    rf"\multicolumn{{4}}{{l}}{{\textit{{Matched cohort A ({na_p*2} patients, {na_p} pairs)}}}}\\",
] + lr_block(lr_match) + [
    r"\bottomrule",
    r"\end{tabular}",
    r"\vspace{2pt}\par\footnotesize\textit{Note}: OR = odds ratio for any psychiatric comorbidity. \textit{Surgery} compares surgical vs.\ non-surgical patients; \textit{Age} per one-year increase; \textit{Female} vs.\ male reference. The matched-cohort model is fit on the 243 PSM pairs from Analysis A and is presented as confirmation that the surgery effect persists after balancing demographic and severity covariates, although attenuated relative to the unadjusted cohort.",
    r"\end{table}",
]
(ANA/"overleaf"/"sections_psm"/"logreg_table.tex").write_text("\n".join(lines))
print("wrote logreg_table.tex")
